<%@include file="/libs/harbor/components/global.jsp" %>

<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">

                <c:choose>
                    <%-- Here we test to see if the user has configured the navigation to
                        be built manually, or automatically. If manual, we populate the nav
                        with nav elements.

                        Each nav element will have its own configuration as well.--%>
                    <c:when test="${globalNavigation.isAutoGenerated}">
                        <%-- Show autogenerated navigation elements--%>
                        <c:if test="${globalNavigation.hasRootNode}">
                            <c:forEach var="currentNode" items="${globalNavigation.rootChildrenAsRenderable}" varStatus="status">
                                ${currentNode.renderedTreeNodeValue}
                            </c:forEach>
                            <%--${globalNavigation.renderableRootNode.renderedTreeNodeChildren}--%>
                        </c:if>
                    </c:when>
                    <c:otherwise>
                        <c:forEach var="currentElement" items="${globalNavigation.navigationElementList}" varStatus="status">
                            <cq:include path="${currentElement.name}" resourceType="harbor/components/content/navigationelement" />
                        </c:forEach>
                    </c:otherwise>
                </c:choose>
            </ul>
        </div>
    </div>
</nav>