<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="cq" uri="http://sling.apache.org/taglibs/sling/1.0" %>
<%@include file="/libs/harbor/components/global.jsp" %>

<ct:component className="com.citytechinc.cq.harbor.components.content.navigation.globalnavigation.GlobalNavigation" name="globalNavigation"/>

<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">

                <c:choose>
                    <%-- Here we test to see if the user has configured the navigation to
                        be built manually, or automatically. If manual, we populate the nav
                        with nav elements.

                        Each nav element will have its own configuration as well.--%>
                    <c:when test="${globalNavigation.isAutoGenerated}">
                        <%-- Show autogenerated navigation elements up to the configured depth level --%>
                        <cq:include path="globalNavigationTree" resourceType=""></cq:include>
                    </c:when>
                    <c:otherwise>
                        <c:forEach var="currentElement" items="${globalNavigation.navigationElementList}" varStatus="status">
                            <cq:include path="${currentElement.name}" resourceType="harbor/components/content/navigationelement" />
                        </c:forEach>
                    </c:otherwise>
                </c:choose>
            </ul>
        </div>
    </div>
</nav>